refactored coupler CHECKSUM fixes to 2024.02-beta1
NOAA-GFDL/FMScoupler pull request #132
Opened 2024-07-02 13:25 UTC by mlee03

This PR should contain the following fixes to 2024.02-beta1

1.  Fix to remove additional ocean-related  `checksums` computations for `flux_ocn2ice+`.  These checksums are not computed in the pre-refactored full coupler.
2. Fix to the timestep for `MAIN_LOOP+` checksums.  The timestep should now correctly print out the coupled timestep value of  `nc`

2024-07-02 17:45 UTC, uramirez8707 requested changes

2024-07-02 17:45 UTC, uramirez8707 commented on full/coupler_main.F90
> +  do_chksum = .True.
This should not be there

2024-07-02 19:19 UTC, mlee03 commented on full/coupler_main.F90
> +  do_chksum = .True.
fixed :woman_facepalming:

2024-07-03 15:36 UTC, rem1776 approved these changes

2024-07-03 15:39 UTC, merged