Updates changelog for 2021.01 release
NOAA-GFDL/FMScoupler pull request #53
Opened 2021-03-05 15:10 UTC by rem1776

2021-03-05 19:05 UTC, ericcsp submitted a review, later dismissed

2021-03-05 19:07 UTC, GFDL-Eric approved these changes

2021-03-05 19:23 UTC, thomas-robinson requested changes
@rem1776 Please send an email confirming that everyone has added their updates to the change log.

2021-03-08 14:21 UTC, thomas-robinson approved these changes

2021-03-08 15:18 UTC, merged