2021.02 release changelog
NOAA-GFDL/FMScoupler pull request #58
Opened 2021-05-17 18:22 UTC by rem1776

Updates changelog for the 2021.02 release

2021-05-17 22:33 UTC, GFDL-Eric approved these changes

2021-05-18 15:38 UTC, wrongkindofdoctor submitted a review, later dismissed

2021-05-19 12:17 UTC, thomas-robinson requested changes

2021-05-19 12:17 UTC, thomas-robinson commented on CHANGELOG.md
> +- Test cases added for varying the latitude of SST maximum in the simpler coupler ice model.
THis should say "simple coupler" not "simpler coupler"

2021-05-19 13:51 UTC, bensonr commented on CHANGELOG.md
> +## [2021.02] - 2021-05-19
Are we going to use the three-field versioning for the release notes?

2021-05-19 13:58 UTC, wrongkindofdoctor approved these changes

2021-05-19 14:25 UTC, thomas-robinson approved these changes

2021-05-20 13:02 UTC, bensonr approved these changes

2021-05-20 16:55 UTC, merged